### ISSUE TITLE
include the "hydra3.jpg" in the data

### ISSUE THREAD

**Issue by zihaozou** [Waller-Lab/MultiWienerNet#1]
Hi, I want to reproduce the "FISTA" result included in the "common" folder. But the sample data "hydra.jpg" is not included in the data folder. Could you update it so I can make the demo work?

Thanks.

**Comment by zihaozou** [comment]
Also, the files "SVD_2_5um_PSF_5um_1_ds4_dsz1_comps_green_SubAvg.mat" and "SVD_2_5um_PSF_5um_1_ds4_dsz1_weights_green_SubAvg.mat" are not included. I try to use the output from "process_psf_for_svd.ipynb" to substitute them and use "real" data to test it, but failed.

**Comment by monakhova** [comment]
We have added hydra3.jpg to the data folder and updated the readme PSF link to include 'SVD_2_5um_PSF_5um_1_ds4_dsz1_comps_green_SubAvg.mat' and 'SVD_2_5um_PSF_5um_1_ds4_dsz1_weights_green_SubAvg.mat'.
